name: test
on: 
 push: 
  branches: feature/test
 workflow_dispatch:

jobs:
 build: 
  runs-on: ubuntu-latest
  if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/test' }}
  steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo Hello, Build!
      
 deploy: 
   needs: [build]
   runs-on: ubuntu-latest
   if: ${{ github.ref == 'refs/heads/feature/test' }}
   steps:
     - name: 'Checkout Github Action' 
       uses: actions/checkout@v4
     - name: Run a one-line script
       run: echo Hello, deploy!
